import { Resend } from "resend";
import nodemailer, { type Transporter } from "nodemailer";
import { env, isProduction } from "../config/env";
import { logger } from "../config/logger";

const resend = env.RESEND_API_KEY ? new Resend(env.RESEND_API_KEY) : null;

/**
 * No RESEND_API_KEY configured (e.g. local dev) — lazily spin up a free
 * Ethereal test inbox instead of a real send. The message never leaves
 * Ethereal's sandbox; the preview link is logged so a developer can read it.
 */
let etherealTransporter: Promise<Transporter> | null = null;
function getEtherealTransporter(): Promise<Transporter> {
  if (!etherealTransporter) {
    etherealTransporter = nodemailer.createTestAccount().then((account) =>
      nodemailer.createTransport({
        host: account.smtp.host,
        port: account.smtp.port,
        secure: account.smtp.secure,
        auth: { user: account.user, pass: account.pass },
      })
    );
  }
  return etherealTransporter;
}

async function sendViaEthereal(to: string, subject: string, html: string, text: string, reason: string) {
  const transporter = await getEtherealTransporter();
  const info = await transporter.sendMail({ from: "CocoSmart <no-reply@cocosmart.test>", to, subject, html, text });
  logger.info(`Email sent to Ethereal test inbox (${reason})`, {
    previewUrl: nodemailer.getTestMessageUrl(info),
  });
}

async function send(to: string, subject: string, html: string, text: string) {
  if (resend) {
    const { error } = await resend.emails.send({ from: env.RESEND_FROM_EMAIL, to, subject, html, text });
    if (!error) return;

    // A real delivery failure must surface loudly in production — faking
    // success there would leave a user waiting forever for an email that
    // never comes. In dev, Resend's sandbox commonly refuses recipients
    // outside the account owner's own address, so falling back to Ethereal
    // keeps the app usable regardless of which email is being tested with.
    if (isProduction) throw new Error(`Resend send failed: ${error.message}`);
    logger.warn("Resend send failed, falling back to Ethereal test inbox", { error: error.message });
    await sendViaEthereal(to, subject, html, text, `Resend rejected the recipient: ${error.message}`);
    return;
  }

  await sendViaEthereal(to, subject, html, text, "no RESEND_API_KEY configured");
}

export const emailService = {
  async sendPasswordResetEmail(to: string, resetUrl: string) {
    await send(
      to,
      "Reset your CocoSmart password",
      `<p>We received a request to reset your CocoSmart password.</p>
       <p><a href="${resetUrl}">Click here to choose a new password</a>. This link expires in 30 minutes.</p>
       <p>If you didn't request this, you can safely ignore this email.</p>`,
      `Reset your CocoSmart password: ${resetUrl} (expires in 30 minutes). If you didn't request this, ignore this email.`
    );
  },

  /** `code` must already be freshly generated by the caller — this function only ever transmits it, never creates it. */
  async sendVerificationEmail(to: string, code: string) {
    await send(
      to,
      "Verify Your CocoSmart Account",
      `<p>Welcome to CocoSmart!</p>
       <p>Thank you for creating your account.</p>
       <p>Your CocoSmart verification code is:</p>
       <p style="font-size: 28px; font-weight: bold; letter-spacing: 4px;">${code}</p>
       <p>This code will expire in 10 minutes.</p>
       <p>If you did not request this account, you can safely ignore this email.</p>
       <p>Thank you,<br/>CocoSmart Team</p>`,
      `Welcome to CocoSmart!\n\nThank you for creating your account.\n\nYour CocoSmart verification code is:\n\n${code}\n\nThis code will expire in 10 minutes.\n\nIf you did not request this account, you can safely ignore this email.\n\nThank you,\nCocoSmart Team`
    );
  },

  /** `code` must already be freshly generated by the caller — this function only ever transmits it, never creates it. */
  async sendLoginOtpEmail(to: string, code: string) {
    await send(
      to,
      "Your CocoSmart Login Code",
      `<p>Here's your CocoSmart sign-in code:</p>
       <p style="font-size: 28px; font-weight: bold; letter-spacing: 4px;">${code}</p>
       <p>This code will expire in 10 minutes.</p>
       <p>If you did not request this, you can safely ignore this email — your account is still secure.</p>
       <p>Thank you,<br/>CocoSmart Team</p>`,
      `Here's your CocoSmart sign-in code:\n\n${code}\n\nThis code will expire in 10 minutes.\n\nIf you did not request this, you can safely ignore this email — your account is still secure.\n\nThank you,\nCocoSmart Team`
    );
  },
};
